### ISSUE TITLE
Highlight/Pulse the stations 

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/license-plate-survey#9]
Have the stations highlight/pulse/change style when a user hovers over the station name in the 'Search Station' drop-down menu

**Comment by rbeatty1** [comment]
Closed via 1d1f52d

**Comment by rbeatty1** [comment]
Well, this was closed with a commit but the solution isn't what was suggested. Forms are stupid and you can seem to add hover functions to the option elements. Station is highlighted when it is selected, but not when mousing over the options. 

Probably for the best, anyway, because the dropdown takes up a bunch of the map and, as previously mentioned, forms are stupid and you can't set a max-height to the menu.
